EXE = samTest
TOOLBASE = WriteFiles ValidationTest ReadFiles BamIndexTest ModifyVar Modify SamFileTest Validate TestEquals TestFilter ShiftIndels TestPileup
SRCONLY = Main.cpp
TEST_COMMAND = ./test.sh

include ../../Makefiles/Makefile.test