EXE = samTest
TOOLBASE = WriteFiles ValidationTest ReadFiles BamIndexTest ModifyVar Modify SamFileTest TestValidate TestEquals TestFilter ShiftIndels TestPileup TestPosList TestCigarHelper TestSamRecordPool TestSamCoordOutput TestSamRecordHelper
SRCONLY = Main.cpp
TEST_COMMAND = ./test.sh

include ../../Makefiles/Makefile.test