TOOLBASE = SampleList VcfFile VcfFileReader VcfFileWriter VcfHeader VcfHelper VcfRecord VcfRecordField VcfRecordFilter VcfRecordGenotype VcfRecordInfo VcfSubsetSamples
HDRONLY = 

include ../Makefiles/Makefile.lib
