# Your Makefile should include this Makefile after defining:
#   TOOLBASE - the base filename for files with .h & .cpp versions
#   SRCONLY - any cpp files without headers.
#   HDRONLY - any header files without cpp
#   VERSION - if not 0.0.1
TOOLBASE ?= 
SRCONLY ?= 
HDRONLY ?= 
VERSION ?= 0.0.1

DIR_PARTS := $(subst /, , $(CURDIR))
DIR_NAME := $(word $(words $(DIR_PARTS)), $(DIR_PARTS))

MAKEFILES_PATH := $(dir $(lastword $(MAKEFILE_LIST)))
include $(MAKEFILES_PATH)Makefile.include

#
# Goncalo's Generic Makefile -- Compiles and installs a Generic Goncalo Tool
# (c) 2000-2007 Goncalo Abecasis
#

$(info curdir: $(CURDIR))

# Source File Set
TOOLHDR = $(TOOLBASE:=.h) $(HDRONLY)
TOOLSRC = $(TOOLBASE:=.cpp) $(SRCONLY)
TOOLOBJ = $(TOOLSRC:.cpp=.o)

HEADERS=$(TOOLHDR)
OBJECTS=$(patsubst %,$(OBJDIR)/%,$(TOOLOBJ))

# make everything
all : $(addprefix $(INCLUDE_PATH)/, $(HEADERS)) $(STAT_GEN_LIB)

install: all

help : 
	@echo "Generic Source Distribution"
	@echo " "
	@echo "This Makefile will compile and install" $(TOOL) "on your system"
	@echo " "
	@echo "Type...           To..."
	@echo "make              Compile everything "
	@echo "make help         Display this help screen"
	@echo "make all          Compile everything "
	@echo "make install      Install binaries in $(INSTALLDIR)"
	@echo "make install INSTALLDIR=directory_for_binaries"
	@echo "                  Install binaries in directory_for_binaries"
	@echo "make clean        Delete temporary files"
	@echo "make test         Execute tests (if there are any)"

$(INCLUDE_PATH)/%.h: %.h
	ln  -s ../$(DIR_NAME)/$< $@

$(OBJECTS): $(TOOLHDR) | $(OBJDIR)

$(OBJDIR):
	mkdir $(OBJDIR)

$(STAT_GEN_LIB) : $(OBJECTS)
	ar -cr $@ $(OBJECTS)
	ranlib $@

clean :
	-rm -f $(OBJDIR)/*.o *~ $(addprefix $(INCLUDE_PATH)/, $(HEADERS))
	$(AR) d $(STAT_GEN_LIB) $(OBJECTS)
	$(RANLIB) $(STAT_GEN_LIB)
	$(MAKE) -C $(TEST_DIR) OPTFLAG="$(OPTFLAG)" --no-print-directory $@

test: all
	@if test -d $(TEST_DIR); \
        then \
	$(MAKE) -C $(TEST_DIR) OPTFLAG="$(OPTFLAG)" --no-print-directory $@; \
        fi

$(OBJDIR)/%.o: %.c
	$(CXX) $(CFLAGS) -o $@ -c $*.c 

$(OBJDIR)/%.o: %.cpp 
	$(CXX) $(CFLAGS) -o $@ -c $*.cpp -DVERSION="\"$(VERSION)\""


.SUFFIXES : .cpp .c .o .X.o $(SUFFIXES)

DFLAGS=-Y

cleandepend:
	        makedepend -- $(DFLAGS) --

depend:
	        makedepend -- $(DFLAGS) -- $(TOOLSRC) >/dev/null 2>&1

# DO NOT DELETE THIS LINE -- make depend depends on it
