# Your Makefile should include this Makefile after defining:
#   TOOLBASE - the base filename for files with .h & .cpp versions
#   SRCONLY - any cpp files without headers.
#   HDRONLY - any header files without cpp
#   VERSION - if not 0.0.1

MAKEFILES_PATH := $(dir $(lastword $(MAKEFILE_LIST)))
include $(MAKEFILES_PATH)Makefile.common

HEADERS=$(TOOLHDR)


.PHONY: all test clean debug profile param install specific_clean

# make everything, ensure headers are in the include direcotry.
param : $(addprefix $(INCLUDE_PATH)/, $(HEADERS)) 

install: opt

# Link into the include directory
$(INCLUDE_PATH)/%.h: %.h
	ln  -s ../$(DIR_NAME)/$< $@


#########
# Build the library
param: $(STAT_GEN_LIB)

# To build the library, build the objects
# Then add them to the library
$(STAT_GEN_LIB): $(OBJECTS)
	ar -cr $@ $(OBJECTS)

specific_clean:
	-rm -f  $(addprefix $(INCLUDE_PATH)/, $(HEADERS))
	$(AR) d $(STAT_GEN_LIB_OPT) $(OBJECTS_OPT)
	$(RANLIB) $(STAT_GEN_LIB_OPT)
	$(AR) d $(STAT_GEN_LIB_DEBUG) $(OBJECTS_DEBUG)
	$(RANLIB) $(STAT_GEN_LIB_DEBUG)
	$(AR) d $(STAT_GEN_LIB_PROFILE) $(OBJECTS_PROFILE)
	$(RANLIB) $(STAT_GEN_LIB_PROFILE)