# This Makefile requires that the following values be previously set.
# LIB_PATH - the path to the base of this tree.

MAKEFILES_PATH := $(dir $(lastword $(MAKEFILE_LIST)))
MAKEFILES_PATH_TMP := $(patsubst %Makefiles/, %, $(MAKEFILES_PATH))
BASE_LIB_PATH := $(dir $(MAKEFILES_PATH_TMP))

STAT_GEN_LIB = $(BASE_LIB_PATH)libStatGen.a
REQ_LIBS = $(STAT_GEN_LIB) $(BASE_LIB_PATH)samtools/libbam.a
OBJDIR = obj
TEST_DIR = test

SAMTOOLS_PATH = $(BASE_LIB_PATH)samtools
INCLUDE_PATH = $(BASE_LIB_PATH)include

include $(MAKEFILES_PATH)Makefile.toolchain

# -fno-ftti is sometimes useful to increase speed
# 2-5%, but makes linking consistently more difficult
#OPTFLAG?=-ggdb -O0
OPTFLAG?=-O4
CXX?=g++ 

# User specific variables listed here.
# USER_INCLUDES =
# USER_COMPILE_VARS = 

CFLAGS?= -Wall  $(OPTFLAG) -I$(INCLUDE_PATH) -I$(SAMTOOLS_PATH) $(USER_INCLUDES) -D__ZLIB_AVAILABLE__  -D_FILE_OFFSET_BITS=64 -D__STDC_LIMIT_MACROS $(USER_COMPILE_VARS)

# default installation directory
INSTALLDIR?=/usr/local/bin
